name: pysera
channels:
  - simpleitk
  - defaults
dependencies:
  - blas=1.0=mkl
  - blosc=1.21.3=h6c2663c_0
  - bottleneck=1.3.5=py37h080aedc_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.7.2=haa95532_0
  - certifi=2022.12.7=py37haa95532_0
  - cfitsio=3.470=h2bbff1b_7
  - charls=2.2.0=h6c2663c_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py37h2bbff1b_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - fftw=3.3.9=h2bbff1b_2
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - fsspec=2022.11.0=py37haa95532_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - imagecodecs=2021.8.26=py37hc0a7faf_1
  - imageio=2.19.3=py37haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - joblib=1.1.1=py37haa95532_0
  - jpeg=9e=h827c3e9_3
  - jxrlib=1.1=he774522_2
  - kiwisolver=1.4.4=py37hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.8=h2bbff1b_5
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.16=h2bbff1b_3
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libtiff=4.2.0=h8a3f274_2
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.10.4=h0ad7f3c_2
  - libxslt=1.1.37=h2bbff1b_1
  - libzopfli=1.0.3=ha925a31_0
  - locket=1.0.0=py37haa95532_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.5.3=py37haa95532_0
  - matplotlib-base=3.5.3=py37hd77b12b_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - munkres=1.1.4=py_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - numexpr=2.8.4=py37h5b0cc5e_0
  - numpy=1.21.5=py37h7a0a035_3
  - numpy-base=1.21.5=py37hca35cd5_3
  - openjpeg=2.4.0=h4afccc4_2
  - openssl=3.0.15=h827c3e9_0
  - packaging=22.0=py37haa95532_0
  - pandas=1.3.5=py37h6214cd6_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre2=10.42=h0ff8eda_1
  - pillow=9.4.0=py37hd77b12b_0
  - ply=3.11=py37_0
  - psutil=5.9.0=py37h2bbff1b_0
  - pyparsing=3.0.9=py37haa95532_0
  - pyqt=5.15.7=py37hd77b12b_0
  - pyqt5-sip=12.11.0=py37hd77b12b_0
  - python=3.7.1=h33f27b4_4
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2022.7=py37haa95532_0
  - pywavelets=1.3.0=py37h2bbff1b_0
  - pyyaml=6.0=py37h2bbff1b_1
  - qt-main=5.15.2=h879a1e9_9
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtwebkit=5.212=h2bbfb41_5
  - scikit-image=0.19.3=py37hd77b12b_1
  - scikit-learn=1.0.2=py37hf11a4ad_1
  - scipy=1.7.3=py37h7a0a035_2
  - setuptools=65.6.3=py37haa95532_0
  - simpleitk=2.1.1.1=py37h82bb817_0
  - sip=6.6.2=py37hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.14=h0416ee5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py37haa95532_0
  - tornado=6.2=py37h2bbff1b_0
  - typing_extensions=4.4.0=py37haa95532_0
  - vc=14.40=h2eaa2aa_0
  - vs2015_runtime=14.40.33807=h98bb1dd_0
  - wheel=0.38.4=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zfp=0.5.5=hd77b12b_6
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
  - pip:
      - dicom2nifti==2.4.11
      - glrlm==0.1.0
      - mahotas==1.4.18
      - nibabel==4.0.2
      - nptyping==2.5.0
      - opencv-python==4.10.0.84
      - pip==24.0
      - pydicom==2.4.4
      - pyhull==2015.2.1
      - pynrrd==1.0.0
      - python-gdcm==3.0.24.1
prefix: C:\Users\liuus\anaconda3\envs\pysera
